// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJmbKQS0Tvqcs7BXC5LOK-INqFPFv0Dw',
    appId: '1:2371357998:web:b8f4456cae0358950dbebf',
    messagingSenderId: '2371357998',
    projectId: 'fireferral',
    authDomain: 'fireferral.firebaseapp.com',
    storageBucket: 'fireferral.firebasestorage.app',
    measurementId: 'G-Z6P4E260NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbLV7b4Y59psn9eUEJspWwdAPgC_mTOtw',
    appId: '1:2371357998:android:29b3c7ba3587d1d20dbebf',
    messagingSenderId: '2371357998',
    projectId: 'fireferral',
    storageBucket: 'fireferral.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqdWDM_JfuLc5-ElrJqqIfpR7oq39KhEk',
    appId: '1:2371357998:ios:35ba055bca38bdca0dbebf',
    messagingSenderId: '2371357998',
    projectId: 'fireferral',
    storageBucket: 'fireferral.firebasestorage.app',
    iosBundleId: 'com.example.fireferral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqdWDM_JfuLc5-ElrJqqIfpR7oq39KhEk',
    appId: '1:2371357998:ios:35ba055bca38bdca0dbebf',
    messagingSenderId: '2371357998',
    projectId: 'fireferral',
    storageBucket: 'fireferral.firebasestorage.app',
    iosBundleId: 'com.example.fireferral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHJmbKQS0Tvqcs7BXC5LOK-INqFPFv0Dw',
    appId: '1:2371357998:web:b8f4456cae0358950dbebf',
    messagingSenderId: '2371357998',
    projectId: 'fireferral',
    authDomain: 'fireferral.firebaseapp.com',
    storageBucket: 'fireferral.firebasestorage.app',
  );
}