#!/bin/bash

echo "🍎 iOS Developer Profile Setup Guide"
echo "===================================="
echo ""
echo "✅ Bundle Identifier updated to: com.fireferral.app"
echo "✅ Xcode workspace opened"
echo ""
echo "📋 Next Steps in Xcode:"
echo ""
echo "1. 🔐 Sign in to Xcode with Apple ID:"
echo "   • Xcode > Settings > Accounts"
echo "   • Click '+' > Apple ID"
echo "   • Sign in with your Apple Developer account"
echo ""
echo "2. 📱 Configure Project Signing:"
echo "   • Select 'Runner' project (blue icon)"
echo "   • Select 'Runner' target"
echo "   • Go to 'Signing & Capabilities' tab"
echo "   • ✅ Check 'Automatically manage signing'"
echo "   • Select your Development Team"
echo "   • Verify Bundle ID: com.fireferral.app"
echo ""
echo "3. 🔧 If you see signing errors:"
echo "   • Make sure you have an active Apple Developer account"
echo "   • Register your device in Apple Developer Portal"
echo "   • Let Xcode create provisioning profiles automatically"
echo ""
echo "4. 🧪 Test the setup:"
echo "   • flutter run -d 'iPhone 16 Pro'"
echo "   • Or build: flutter build ios --release"
echo ""
echo "📱 Current Configuration:"
echo "   Bundle ID: com.fireferral.app"
echo "   Display Name: FiReferral"
echo "   Google OAuth: Configured"
echo "   Firebase: Configured"
echo ""
echo "🚀 Once signing is configured, you can:"
echo "   • Run on simulator: flutter run -d 'iPhone 16 Pro'"
echo "   • Build for device: flutter build ios --release"
echo "   • Archive for App Store: Product > Archive in Xcode"